site_name: ESP IoT Framework
nav:
  - Home: index.md
  - Software Planning: 
    - Class - ConnectionHandler: software-planning/connection-handler.md
    - Sensors: software-planning/sensors.md
  - Framework Documentation:
    - ESP Core:
      - Overview: core/overview.md
      - Getting Started: core/getting_started.md
      - Core Classes:
        - Config: core/core_classes/esp_config.md
        - Spiffs: core/core_classes/esp_spiffs.md
        - Wifi: core/core_classes/esp_wifi.md
        - Connection Handler: core/core_classes/esp_connection_handler.md
        - Keys: core/core_classes/esp_keys.md
        - Logger: core/core_classes/esp_logger.md


repo_url: https://github.com/ECE-IoT/esp-iot-framework

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - git-revision-date
  - mkdocstrings
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(window.localStorage.getItem('/.__palette')).index == 1) ? 'dark' : 'light'

markdown_extensions:
  - footnotes
  - admonition
  - def_list
  - attr_list
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
